---
- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'python-pip' ]

- name: Add docker gpg apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install docker
  apt: update_cache=yes name=docker-ce state=latest

- name: Install docker modules for python
  pip: name={{ item }}
  loop: [ 'docker', 'docker-compose' ]

- name: Add vagrant user to docker group
  user:
    name: "vagrant"
    groups: docker
    append: true
